version: '3.9'
services:
    ibot-gpt:
        image: 'ghcr.io/slendymilky/torupto:latest'
        container_name: torupto
        restart: always
        env_file:
            - stack.env
        volumes:
            - torupto_db:/torupto/database

volumes:
  torupto_db: {}