name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Convert Repository Owner to Lowercase
        id: lowercase
        run: |
          REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=$REPO_OWNER" >> $GITHUB_ENV

      - name: Build and Push Docker Image to GitHub Container Registry
        run: |
          docker build . --tag ghcr.io/${{ env.REPO_OWNER }}/torupto:latest
          docker tag ghcr.io/${{ env.REPO_OWNER }}/torupto:latest ghcr.io/${{ env.REPO_OWNER }}/torupto:${{ env.VERSION }}
          docker push ghcr.io/${{ env.REPO_OWNER }}/torupto:latest
          docker push ghcr.io/${{ env.REPO_OWNER }}/torupto:${{ env.VERSION }}
